### ISSUE TITLE
Missing network discovery on 4.4 Template

### ISSUE THREAD

**Issue by Zolpho** [albinbatman/zabbix-qnap-template#1]
Thank you for your job. Works well on a TS-h886.

Any chance to add "Network interfaces discovery" in Discovery rules?
I would like to monitor network bandwidth and create some graphs.

Thanks
Lorenzo

**Comment by albinbatman** [comment]
Hi @Zolpho,

I will look into the MIB file and add this feature.

**Comment by albinbatman** [comment]
Hi again,

I do not see a lot of possibility to gather data but at least it has sent and received statistics. I will add the following to the template and push for version 4.x and 5.x.

![image](https://user-images.githubusercontent.com/15878764/101092685-50293880-35ba-11eb-90ee-c75d6da05159.png)
