### ISSUE TITLE
Import failed in Zabbix 6.0.4: Host "Template Module Generic SNMP" does not exist 

### ISSUE THREAD

**Issue by landure** [albinbatman/zabbix-qnap-template#10]
on a new Zabbix 6.0.4 Docker install, when importing the template for v6, this error appears:

Incorrect trigger expression. Host "Template Module Generic SNMP" does not exist or you have no access to this host.

Attached is the template file I downloaded from share.zabbix.com, and tried to import.

[template_qnap_(snmpv2).zip](https://github.com/albinbatman/zabbix-qnap-template/files/8812740/template_qnap_.snmpv2.zip)

Thank you for your hard work.

**Comment by landure** [comment]
The correct template name seems to be "Network Generic Device SNMP".

**Comment by albinbatman** [comment]
Hello @landure,

I see that you mentioned the following
> Attached is the template file I downloaded from share.zabbix.com, and tried to import.

I do not update the templates on share.zabbix.com as it is about to be EOL, or rather closed in favor of Zabbixs own template repository on GitHub.

Are you able to import the following template [template.yml](https://github.com/albinbatman/zabbix-qnap-template/blob/master/zabbix-6.x/Firmware%204.5.2%20or%20higher/template.yaml) in your Zabbix installation?

**Comment by landure** [comment]
Hi,

now the error is "Cannot import template "Template SNMP QNAP", linked template "ICMP Ping" does not exist."

On Zabbix 6.0 , the ICMP template is "Template Module ICMP Ping"

Thank you for you reply.

**Comment by albinbatman** [comment]
> Hi,
> 
> now the error is "Cannot import template "Template SNMP QNAP", linked template "ICMP Ping" does not exist."
> 
> On Zabbix 6.0 , the ICMP template is "Template Module ICMP Ping"
> 
> Thank you for you reply.

I will adjust template so it does not rely on the default template, seems Zabbix keeps changing them.

**Comment by landure** [comment]
To add a new information to this issue, i've installed a fresh Zabbix Server 6.0.7, and the ping template is now "ICMP Ping". "Template Module ICMP Ping" may have been a bug present in early Zabbix 6.0 databases.
