### ISSUE TITLE
Rerquesting new template for QNAP NAS FW QTS 4.5.2

### ISSUE THREAD

**Issue by amol-narkhede** [albinbatman/zabbix-qnap-template#3]
Hello there,
I am a Product Manager working with QNAP. We have released a new FW version of our NAS QTS 4.5.2 recently. 
We have done a major upgrade to SNMP MIB with this version. 
I would like to request your support to update the new Zabbix Template to support this new version of the firmware. 

Many of our customers who use Zabbix are requesting for this update. So kindly help. 

Details: https://www.qnap.com/en/release-notes/qts/4.5.2.1630/20210406
My email: amolnarkhede@qnap.com

Please feel free to contact me. 

Regards,
Amol Narkhede
Product Manager.
QNAP Systems Inc Taipei.

**Comment by amol-narkhede** [comment]
Dear Albin,
Thank you for contacting me on my company email. 
As discussed we are ready to provide you access to our device. I have already sent you multiple mails. Not sure if you are receiving those. Kindly reply.

Regards,
Amol

**Comment by albinbatman** [comment]
NAS has been received and I will begin working to support the new version of the firmware. Me and Amol exchange correspondence through e-mail. I will be reaching out to you during next week.

**Comment by amol-narkhede** [comment]
Noted Albin.
Thank you.

Amol

**Comment by amol-narkhede** [comment]
Hello Albin,
Its been a long time we have been following up with you. 
We have even sent NAS to you so that you can help with the above query. But even after following up for long time, we are not getting any response form you. Kindly do let us know if we should contact anyone else, who can actually  work on this matter and respond to our mails. 

@Zabbix: Please check this. We are not getting ant response or support. You may assign any other person. 
Thank you. 

Amol

**Comment by albinbatman** [comment]
Hi @amol-narkhede,

Many apologies for the delay, it has been due to various factors. I have now pushed a template for zabbix-6.x for the new firmware OIDs. Do you want backward compatibility with lower Zabbix versions?

**Comment by amol-narkhede** [comment]
Hi Albin, Yes we need to have backward compatibility.

**Comment by amol-narkhede** [comment]
Do you want backward compatibility with lower Zabbix versions?
*Answer*: *Yes*, we would like to have it, Albin. Please do help.

Regards,
Amol
