### ISSUE TITLE
Import error in Zabbix 5.0

### ISSUE THREAD

**Issue by D4rkX0** [albinbatman/zabbix-qnap-template#6]
Hello,

i have a problem to import the 5.x template in Zabbix 5.0

Error : Invalid tag "/zabbix_export/version": unsupported version number.

**Comment by albinbatman** [comment]
Hi,

Which template are you importing?

**Comment by D4rkX0** [comment]
Hi,

The zabbix-5.x template.

https://github.com/albinbatman/zabbix-qnap-template/tree/master/zabbix-5.x

**Comment by albinbatman** [comment]
Hi again,

can you open it and manually adjust the following:

```xml
<version>5.2</version>
```

to

```xml
<version>5.0</version>
```

and then try importing it again?

**Comment by D4rkX0** [comment]
Hi,

i got this error.

Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(4)/item_prototypes/item_prototype(1)/preprocessing/step(1)": unexpected tag "parameters".

**Comment by D4rkX0** [comment]
Hi,

i used your version from : https://share.zabbix.com/storage-devices/qnap/qnap-template-snmpv2

Imported well. 

Thanks for the great job.

**Comment by venzislav** [comment]
I also cannot import 5.x template - even after I modify to be 5.0 version.
But I import 4.x template and it works well - only one bug and I will make new report for it.

**Comment by albinbatman** [comment]
Hi,

Try one of the following from [releases](https://github.com/albinbatman/zabbix-qnap-template/releases/tag/v1.0.2).
