### ISSUE TITLE
Wrong size for Volume X, wrong uptime and cannot import 5.x to Zabbix 5.0 for QNAP TS-453D

### ISSUE THREAD

**Issue by venzislav** [albinbatman/zabbix-qnap-template#7]
Hi, 
I use your template for home nas server  QNAP TS-453D.
The first bug is that I cannot import 5.x template to 5.0 zabbix even after modify inside to be for ver. 5.0 - I manage to import 4.x image and it is working now.
Second bug is that I see the size of "Volume X" in GB despite it must be in TB :

  |   |   | Volume 2: Capacity | 2021-11-29 12:17:01 | **1.78 GB** |   | Graph
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | Volume 1: Status | 2021-11-29 12:17:01 | Ready |   | History
  |   |   | Volume 1: Name | 2021-11-29 12:02:00 | DataVol1 |   | History
  |   |   | Volume 1: Free size in % | 2021-11-29 12:16:15 | 29 |   | Graph
  |   |   | Volume 1: Free size | 2021-11-29 12:17:01 | 1.04 GB | -3.24 KB | Graph
  |   |   | Volume 1: Capacity | 2021-11-29 12:17:01 | **3.56 GB** |   | Graph

but next data is correct here :

  |   |   | RAID 2: Capacity | 2021-11-29 12:02:01 | **1.81 TB |**   | Graph
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | RAID 1: State | 2021-11-29 12:17:01 | Ready |   | History
  |   |   | RAID 1: Level | 2021-11-29 12:02:01 | 1 |   | Graph
  |   |   | RAID 1: Free size | 2021-11-29 12:02:01 | 0 B |   | Graph
  |   |   | RAID 1: Capacity | 2021-11-29 12:02:00 | **3.63 TB |**   | Graph

and the last bug for now is that uptime of devise is not correct also - is says :

  |   |   | Device uptime | 2021-11-29 12:30:01 | 10:26:29 | +00:00:31 | Graph
-- | -- | -- | -- | -- | -- | -- | --

but the real time is :

System up time	5 Days 23 Hour 58 Minute(s)

Thanks in advance !

**Comment by dannykorpan** [comment]
Same problem here.
